export const bucketName = 'healthtar-storage'
export const profileImgMiddlePath = 'profile-images'
export const presentImgMiddlePath = 'present-images'
export const goalImgMiddlePath = 'goal-images'
export const postImgMiddlePath = 'post-images'
